# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a75f772ce9c0892a7c6f5ab817479133c84b90f22661234a2f443e929ee56d4061c505de483ce24f060d912c67ca62eff2c492fb24d8d3aef0682df3da252c1f

test:
  secret_key_base: 2fcf421091f02fc2bde2226d9f7f55db6461b6e245a2a4ebdd532f7c2b84e1834dc4252cc1c72bd2d890664f8b2ce721ceb082fd40f6d933a1e13014dea9034d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
